from __future__ import annotations

STREAM_W = 128
PRICE_W = 32
QTY_W = 32
TS_W = 32
EVENT_FLAGS_W = 23
DECISION_PIPE_STAGES = 3

DEFAULT_SPREAD_THRESHOLD = 4
DEFAULT_IMBALANCE_THRESHOLD = 2
DEFAULT_MAX_ORDERS_PER_WINDOW = 4
DEFAULT_WINDOW_CYCLES = 16
DEFAULT_INGRESS_FIFO_DEPTH = 8
ORDERBOOK_MEM_DEPTH = 1

BASE_QTY = 4
MIN_QTY = 1
MAX_QTY = 16
